### ISSUE TITLE
assets

### ISSUE THREAD

**Issue by idindrakusuma** [Invitato/public#1]
![FOTO TANDA KASIH](https://github.com/Invitato/public/assets/10141928/521b49e5-fb3b-40db-b36e-8017a0ffe756)

**Comment by zaanfa** [comment]
GIF Rafif & Pute
https://github.com/Invitato/public/assets/26963539/1926f03a-9439-44dd-b8d9-be43e052b452

**Comment by basirudinansor** [comment]
Gif Ivan & Vania

https://github.com/Invitato/public/assets/103095433/76b35f52-ace2-49b9-bcc2-68d51ba13f13

**Comment by basirudinansor** [comment]
Covid for Hendry Clarissa
![147309640-90f4ada7-05d6-4b4d-a377-ad636d4d177c](https://github.com/Invitato/public/assets/103095433/20f04f29-1531-4bc2-a5e5-c7e3ce1c2805)
![147309670-887acb92-a3b6-4f9b-b78c-839c7d466b5c](https://github.com/Invitato/public/assets/103095433/c7d17d12-c32f-44a1-834a-af73e655b0b6)

**Comment by idindrakusuma** [comment]
![Copy of 1E0A9427 (1)](https://github.com/Invitato/public/assets/10141928/99f251fd-0a5b-406d-92e0-523e19268335)

**Comment by zaanfa** [comment]
gif Dion & Kristy

https://github.com/Invitato/public/assets/26963539/01960940-8ee9-4aef-8ff7-7417619e3f2a

https://github.com/Invitato/public/assets/26963539/2c0c48cd-5ca3-464f-89be-83c805f3bfc6

**Comment by basirudinansor** [comment]
![IMG_8459 pure (1)](https://github.com/Invitato/public/assets/103095433/70308deb-d129-4dc8-a2d0-40b6f6f13e6f)

**Comment by basirudinansor** [comment]
![3 (1)](https://github.com/Invitato/public/assets/103095433/45793408-c50a-4c2d-a6c5-2f7eee0c3baf)

**Comment by zaanfa** [comment]
gif gabby-jeff
![gif](https://github.com/Invitato/public/assets/26963539/b188af6a-1e01-4e35-ae0b-313d35a330f4)

gift-alt
![gif-alt](https://github.com/Invitato/public/assets/26963539/3fb2da76-b903-4b88-9bb1-bd7eddcb307d)

**Comment by zaanfa** [comment]
gif vincent-cecilia

https://github.com/Invitato/public/assets/26963539/0a795698-fe8b-4cbc-b28e-ebf1fc3758a9

**Comment by zaanfa** [comment]
gif saras-fauby

https://github.com/Invitato/public/assets/26963539/41548502-336a-4d07-ae3a-b112d86f21e2

**Comment by basirudinansor** [comment]
![PJCLB-400=](https://github.com/Invitato/public/assets/103095433/81ee4935-8036-4b22-b8c1-81eafe03d79d)

**Comment by zaanfa** [comment]
gif victor-yolanda
https://github.com/Invitato/public/assets/26963539/77e4d8c5-5ab7-4e1d-b9ad-4ddde1cd92d5

**Comment by basirudinansor** [comment]
https://github.com/Invitato/public/assets/103095433/cb5a531e-16f4-457b-8d98-bda43dd8d8dc

**Comment by basirudinansor** [comment]
GIF Ferin Nouval

https://github.com/Invitato/public/assets/103095433/f851ca35-fdbf-4936-b65a-f68d73625ccb

**Comment by basirudinansor** [comment]
https://github.com/Invitato/public/assets/103095433/4cacde78-f76a-4013-9407-5e4b7630c7ea

**Comment by basirudinansor** [comment]
https://github.com/Invitato/public/assets/103095433/cff46c5c-ddc9-4d5f-a728-3245a17b7023

**Comment by basirudinansor** [comment]
https://github.com/Invitato/public/assets/103095433/c5945ed8-bcc3-4e7c-a9d0-9496d08e3590

**Comment by basirudinansor** [comment]
https://github.com/Invitato/public/assets/103095433/21471dea-22b2-44ef-ae41-659c3beee4e6

**Comment by basirudinansor** [comment]
![foto footer potrait](https://github.com/Invitato/public/assets/103095433/8a676975-f807-434c-9c5d-78d3a1c8f64f)
![Foto Groom](https://github.com/Invitato/public/assets/103095433/7cbe8c03-4c12-4a4b-b35d-79e6ad67ce4b)
![SEO](https://github.com/Invitato/public/assets/103095433/b55d69cc-77f4-4fb2-b802-abc5101decdb)
![Foto bride](https://github.com/Invitato/public/assets/103095433/cf7b3927-3600-4bcc-bdbd-ce7cb487a6db)
![Foto cover dalam potrait](https://github.com/Invitato/public/assets/103095433/6e890537-731a-427e-b952-87d43023549b)
![foto cover galery 1](https://github.com/Invitato/public/assets/103095433/e10987e7-aa0d-41b0-9d76-335104f19f5b)
![foto cover galery 2](https://github.com/Invitato/public/assets/103095433/b56eee0c-69e9-4035-b310-4d5f2e6b40b1)
![Foto Cover Potrait](https://github.com/Invitato/public/assets/103095433/200533fa-de6a-4e64-93de-8462c28ca4d1)
![foto desktop view landscape](https://github.com/Invitato/public/assets/103095433/0203cd4b-42ea-4a75-b954-82fe75d28abc)

**Comment by zaanfa** [comment]
Anastiti Hilman
Cover Gallery 1
![g1-new](https://github.com/Invitato/public/assets/26963539/7a14515c-45d2-4591-aa94-7b29f635412c)

Cover Gallery 2
![g2-new](https://github.com/Invitato/public/assets/26963539/84a585f1-58e7-4d95-bcbe-4fc0f192f3aa)

Bg Gift
![gift-new](https://github.com/Invitato/public/assets/26963539/6f5ba6d0-2a49-43f8-9f2b-8ecc2f61ea73)

**Comment by zaanfa** [comment]
gif valen-valent
![gif](https://github.com/Invitato/public/assets/26963539/b8cddcc8-9d67-4c98-a384-0bb8563c412f)
