### ISSUE TITLE
elite design

### ISSUE THREAD

**Issue by idindrakusuma** [Invitato/public#6]
list asset of elite design

![image](https://github.com/Invitato/public/assets/10141928/096f23cc-a639-4677-a131-2efffa1e8c0e)

![image](https://github.com/Invitato/public/assets/10141928/90b051c7-0863-4dc3-946c-27570d8560c7)

**Comment by idindrakusuma** [comment]
![ori-1](https://github.com/Invitato/public/assets/10141928/39cfd829-7eb3-4148-85af-1f804e5f9d5a)
![ori-2](https://github.com/Invitato/public/assets/10141928/169e4109-e0b2-4469-afac-86fb0246cd39)

**Comment by idindrakusuma** [comment]
![extend-1](https://github.com/Invitato/public/assets/10141928/f4ce0ecc-ea90-4639-b3a0-d47d633859e2)
![extend-2](https://github.com/Invitato/public/assets/10141928/844feaf3-fc29-4a8a-9bb5-7fa2bbad17b9)

**Comment by basirudinansor** [comment]
GIF Alya Fahmi

https://github.com/Invitato/public/assets/103095433/991ad813-2900-4462-b64b-e988cc103c05

**Comment by basirudinansor** [comment]
https://github.com/Invitato/public/assets/103095433/beccbd2e-e6ef-4e2c-94da-46142f9d65cc
